# Generated by Django 4.0.5 on 2022-06-11 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('price', models.IntegerField()),
                ('count', models.SmallIntegerField()),
                ('availability', models.BooleanField(default=True)),
                ('description', models.TextField()),
                ('processor', models.CharField(max_length=20)),
                ('cpu', models.CharField(max_length=20)),
                ('processor_cache', models.SmallIntegerField()),
                ('screen_type', models.CharField(max_length=20)),
                ('screen_size', models.SmallIntegerField()),
                ('brand', models.CharField(max_length=20)),
                ('photo', models.ImageField(upload_to='photos/shop/%Y/%m/%d/')),
            ],
        ),
    ]
